### ISSUE TITLE
How to open the binary weights file?

### ISSUE THREAD

**Issue by wsyzzz** [simo23/tinyYOLOv2#1]
Hi, Simo! You've done an amazing project and really help me a lot! I have a small question that how do you open the binary weights file like tiny-yolo-voc.weights? I wanted to edit it with 'vi tiny-yolo-voc.weights' or 'gedit tiny-yolo-voc.weights' in Ubuntu 16.04 but failed. Does it need any special applications to open it? Thx.

**Comment by simo23** [comment]
Hi @wsyzzz , thanks!

As the name says the file is binary, which means that it contains only zeros and ones. It is basically a list of float32 numbers saved in binary format, which after the conversion one after the other define the single parameters of the network. So there is nothing human-readable to see into that file :) The only thing you can do is importing it with:

        loaded_weights = np.fromfile(weights_path, dtype='f')

which will convert the binary numbers to float32 numbers readable in numpy. Now you have a list of numbers that you can see, but nothing more. By knowing the order in which they have been saved by the author of the file we can then assign their value into the right parameter of our network.

**Comment by wsyzzz** [comment]
@simo23 Thanks for your response! I get it!
