### ISSUE TITLE
test.py crashes

### ISSUE THREAD

**Issue by srohit0** [simo23/tinyYOLOv2#11]
`[~/tinyYOLOv2]$ python3 test.py`

> Total number of params = 15867885
> 2018-12-25 11:34:48.750981: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> Looking for a checkpoint...
> No checkpoint found!
> Loading weights from file and creating new checkpoint...
> Total number of params to load = 15867885
> Loading 496 weights of conv1 ...
> Loading 4736 weights of conv2 ...
> Loading 18688 weights of conv3 ...
> Loading 74240 weights of conv4 ...
> Loading 295936 weights of conv5 ...
> Loading 1181696 weights of conv6 ...
> Loading 4722688 weights of conv7 ...
> Loading 9441280 weights of conv8 ...
> Loading 128125 weights of conv9 ...
> Final offset = 15867885
> Total number of params in the weight file = 15867885
> Saving new checkpoint to the new checkpoint directory ./ckpt/ !
> Preprocessing...
> Traceback (most recent call last):
>   File "test.py", line 249, in <module>
>     tf.app.run(main=main) 
>   File "/home/amd/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "test.py", line 237, in main
>     preprocessed_image = preprocessing(input_img_path,input_height,input_width)
>   File "test.py", line 82, in preprocessing
>     resized_image = cv2.resize(input_image,(input_height, input_width), interpolation = cv2.INTER_CUBIC)
> cv2.error: OpenCV(3.4.4) /io/opencv/modules/imgproc/src/resize.cpp:3784: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by prateethvnayak** [comment]
@srohit0 check the image file in test.py . Update it to some other file if that image does not exist in the folder. 

close if solved.
