### ISSUE TITLE
Any update on training part

### ISSUE THREAD

**Issue by MinLiAmoy** [simo23/tinyYOLOv2#2]
@simo23 Thanks for your wonderful work!
I am trying the low-precision version of tiny-yolo recently, and I wonder if there is any update on training part.
Best wishes!

**Comment by simo23** [comment]
Thanks @MinLiAmoy!
Unfortunately there isn't any update on the training part, I need to write it in the README.

**Comment by MinLiAmoy** [comment]
@simo23 thanks for your reply~
