### ISSUE TITLE
class prediction in test.py

### ISSUE THREAD

**Issue by leadcain84** [simo23/tinyYOLOv2#3]
thanks you for your code.

in the test.py, class prediction is calculated per a grid cell.
why is it?
i think, it is calculated based on all grid cell.

**Comment by simo23** [comment]
Hi, @leadcain84,

The predictions have shape 13x13x125. 13x13 are the grid cells, in each cell there are 5 anchors. The predictions can be seen also as 13x13x5x25 = 13x13x5x(20+5). The 20 corresponds to the class predictions, which are computed **for all of the 13x13 cells and for all 5 anchors defined in each cell**. 

The proof and reason why can be found in the original paper (https://arxiv.org/abs/1612.08242) in section 2. In particular in the paragraph "Convolutional with anchor boxes" where the authors say "when we move to anchor boxes we also decouple the class  prediction  mechanism  from  the  spatial  location  and instead predict class and objectness for every anchor box."

Does this help?

**Comment by leadcain84** [comment]
Hi simo23
Thank you for your answer.
I already solved the question.
That was my miss understanding.
your source code is very helpful for me.

**Comment by simo23** [comment]
Thanks @leadcain84!
