### ISSUE TITLE
Tiny Yolo is very slow on  Jetson TX1 

### ISSUE THREAD

**Issue by parvez2307** [simo23/tinyYOLOv2#6]
hi simo,
hw r u doing....

i have taken your tinyYOLOv2 and start running on my GPU(GTX-980), its working good. But i need the same tiny-yolo to be implemented on Jetson TX1. I have tried that, but it was very slow it was around 2 fps but where as in my GPU its touching to 30fps. Earlier to tiny-yolo i have done people detection and is working well on TX1. My  Jetson TX1 board is of 4GB RAM and even i have swapped with 16GB(total 20GB). So, could you please suggest me  ways to increase the speed. 

implemented on : 
Ubuntu 16.04
Tensorflow 1.0
Python 2.7
OpenCV 3.0
Numpy 1.13.0

thanks in advance,
parvez.

**Comment by simo23** [comment]
Hi,

I do not have any experience on embedded platforms like the Jetson. By googling a little bit other people seem to have encountered the same [issue](https://devtalk.nvidia.com/default/topic/1027819/jetson-tx2/object-detection-performance-jetson-tx2-slower-than-expected/). Please consider to check the suggestions made by the NVIDIA team to improve the speed.

Good luck,
Andrea
