### ISSUE TITLE
How to use a model already trained on custom dataset

### ISSUE THREAD

**Issue by izesaon** [simo23/tinyYOLOv2#8]
hi, just wondering if i can use the weights generated on retraining the tiny yolo v2 on my own dataset for your code?

**Comment by simo23** [comment]
Hi,

yes you can. You must be careful to specify the correct paths in the function weights_loader.load() in order to make it find the file. The important bit is this one:

```
def load(sess,weights_path,ckpt_folder_path,saver):

    if(os.path.exists(ckpt_folder_path)):
        print('Found a checkpoint!') 
        checkpoint_files_path = os.path.join(ckpt_folder_path,"model.ckpt")
        saver.restore(sess,checkpoint_files_path)
        print('Loaded weights from checkpoint!') 
       return True
```

- If you have a **tf ckpt**, be sure that the code enters in that "if" and finds the ckpt.
- If you have a **binary file** than it should work too! It will load the weights outside that "if"

**Comment by izesaon** [comment]
hi, thanks for the prompt response. may I check if i use the repository https://github.com/bastiaanv/Yolov2-tiny-tf-NCS which was inspired by your repository, is there any reason why the predictions generated are nan? i m trying to sieve out the sections of the code where i would need to modify to be able to successfully do live object detection with my own weights instead of the provided ones from darknet, thanks so much for the help!

**Comment by simo23** [comment]
Well there could be a lot of reasons why you get nan. Did you try to use your trained model in the repository which you used to train? You have to be sure that the training was done well. If you see that there are no nans there, then maybe there is an issue with the save/restore of the ckpt. But do you have the tf ckpt or binary file?

**Comment by izesaon** [comment]
Sorry what i meant is, are there specific sections of the code that i have to modify since i am training on 2 classes. my weights are fine like there's no nan only the predictions.

**Comment by izesaon** [comment]
in nets.py, line 125, b9 = bias_variable([125]), is this 125 specific to the 20 classes you tested the code you built?

**Comment by simo23** [comment]
Yes! As said in another issue:

The predictions have shape 13x13x125. 13x13 are the grid cells, in each cell there are 5 anchors. The predictions can be seen also as 13x13x5x25 = 13x13x5x(20+5). The 20 corresponds to the class predictions, which are computed for all of the 13x13 cells and for all 5 anchors defined in each cell.

So you need to change that accordingly.

**Comment by izesaon** [comment]
hi thanks, is there any other section of the code with the problem? my generated kernel weights, bias and offset looks fine using your code but predictions remain at nan

**Comment by izesaon** [comment]
For instance, my retrained model has 2 classes. Which part of the code should i modify? I am in the process of identifying but I may have missed out since I do not fully understand the code.

**Comment by simo23** [comment]
You should also need to modify net.py here:

```
#15 conv9   125  1 x 1 / 1    13 x  13 x 1024   ->    13 x  13 x125
w9 = weight_variable([1,1,1024,125])
b9 = bias_variable([125])
h9 = tf.nn.conv2d(o8, w9, strides=[1, 1, 1, 1], padding='SAME') + b9
# Linear output!
o9 = h9
n_params = n_params + 1*1*1024*125 + 125 # There is not batch norm, so n_params is: kernel_size + n_biases
```

By the way it is strange that it does not give any error while loading the weights!

**Comment by izesaon** [comment]
Can I check that your code is not specific to any weights? I am referring to load_conv_layer_bn() in your code. I tried to load weights from pjreddie.com/media/files/yolo9000.weights but i got a nan error for the weights.

**Comment by simo23** [comment]
You have to be extremely sure that you are using tiny-YOLOv2 and not something else. You need to have the exact same architecture as defined in the cfg file otherwise nothing will remotely work. The weights_loader.load() fn will not raise any errors, you have to make sure that what you are doing is correct.

**Comment by izesaon** [comment]
Sorry what I mean is, I am surprised that even the weights file from the darknet github has nan :/

**Comment by izesaon** [comment]
can i confirm which cfg file are you referring to?

**Comment by simo23** [comment]
I am not surprised, this code is done for a specific architecture. If you want to use the weights of another architecture, you will get errors. 

**Please** read the README **carefully**. Your questions are already answered there.

**Comment by izesaon** [comment]
Hi I actually use the weights generated by this guy who said he used tiny yolo v2, https://medium.com/@manivannan_data/how-to-train-yolov2-to-detect-custom-objects-9010df784f36

Sorry for the trouble and thanks for the clarification:)

**Comment by simo23** [comment]
Unfortunately I cannot check how he did it. If the cfg file that he used is tiny-YOLOv2 then everything should be fine. One thing that you can check is that the number of parameters in the binary file is exactly the same as the one of the network. There is a print at the bottom of the load() fn, try to check that

**Comment by izesaon** [comment]
Hi, however the cfg file will be modified since he is retraining it right? Is that fine for your code? For instance, he would need to change filter to suit number of classes.

**Comment by izesaon** [comment]
I would like to check if the model you built, the parameters such as filter size etc are they from the darknet code or dark net config file. Thanks sorry for the trouble!

**Comment by simo23** [comment]
If you have a different number of classes the only thing that should change are the shape of the last layer outputs. This must be changed in both the network definition (net.py) and weights loader function. 

In theory all the other things in the network ( if it is tinyYOLOv2) should be exactly the same.

I can tell you that my implementation is the same as the darknet one. I know it for sure because I tested the cfg, number of parameters as well as I can obtain good results while testing.

**Comment by izesaon** [comment]
Hi thanks so much for your help. I suspect that the nan error is due to the different config file used by the repo I followed. I will try it out later. Thanks so much for the help, hope it goes well:)

**Comment by simo23** [comment]
Unfortunately the error could be in the smallest detail! 

Good luck

**Comment by izesaon** [comment]
hi @simo23 can i just check what is offsets in the neural network layers?
